apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-backend-app-deployment
  labels:
    io.kompose.service: temp-backend-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # how many pods we can add at a time
      maxUnavailable: 1  # how many pods can be unavailable during the rolling update
  minReadySeconds: 5
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
        io.kompose.service: temp-backend-app
  template:
    metadata:
      labels:
        io.kompose.service: temp-backend-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - agentpool
      containers:
      - name: temp-backend-app
        args:
          - "-c"
          - "dotnet EPIC.TEMP.API.Core.dll"
        command: 
          - /bin/sh
        image: tempdevelop.azurecr.io/temp-backend-core-app:6
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /swagger
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: "repo_project"
          value: "temp-backend-app"
        # volumeMounts:
        #   - name: appsettings
        #     mountPath: "<<path to appsettings.json>>"
        #     subPath: appsettings.json
        #     readOnly: true
      restartPolicy: Always
      # volumes:
      # - name: appsettings
      #   secret:
      #     secretName: appsettings
      #     items:
      #       - key: appsettings.json
      #         path: appsettings.json