apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: bis-frontend-app
  name: bis-frontend-app
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: bis-frontend-app